FROM python:3.9-slim
WORKDIR /app/
COPY config config
COPY data data
COPY trained_models trained_models
COPY helper_classes.py helper_classes.py
COPY helper_functions.py helper_functions.py
COPY models.py models.py
COPY predict.py predict.py
COPY prepare_data.py prepare_data.py
COPY requirements.txt requirements.txt
COPY SETTINGS.json SETTINGS.json
COPY train_predict.py train_predict.py
COPY train.py train.py
RUN pip install -r requirements.txt
ENTRYPOINT ["python", "./train_predict.py", "--action"]